<html>
	<head>
		<title>Eway Bill PDF</title>        
	</head>
	<body>
        <div class="border-dark m-5 p-5">
            <div class="text-center">
                <img src="<?=$qrCode?>" width="130">
            </div>
            
            <table class="table table-borderless table-outer-bordered m-b-5">
                <tr>
                    <th class="bg-light text-center" colspan="2">PRINT E-WAY BILL</th>
                </tr>
                <tr>
                    <th style="width:35%;">E-Way Bill No. </th>
                    <td><?=$ewbData->eway_bill_no?></td>
                </tr>
                <tr>
                    <th>E-Way Bill Date </th>				
                    <td><?=date("d/m/Y h:i:s A",strtotime($ewbData->eway_bill_date))?></td>
                </tr>
                <tr>
                    <th>Generated By </th>				
                    <td><?=$ewbData->json_data->fromGstin?> - <?=$ewbData->json_data->fromTrdName?></td>
                </tr>
                <tr>
                    <th>Valid From </th>				
                    <td><?=date("d/m/Y h:i:s A",strtotime($ewbData->eway_bill_date))?> [<?=$ewbData->json_data->transDistance?> Kms]</td>
                </tr>
                <tr>
                    <th>Valid Until </th>				
                    <td><?=date("d/m/Y h:i:s A",strtotime($ewbData->valid_up_to))?></td>
                </tr>
            </table>

            <table class="table table-borderless table-outer-bordered m-b-5">                    
                <tr>
                    <th class="text-center bg-light"colspan="2">PART - A</th>
                </tr>
                <tr>
                    <th>GSTIN of Supplier </th>				
                    <td><?=$ewbData->json_data->fromGstin?> - <?=$ewbData->json_data->fromTrdName?></td>
                </tr>
                <tr>
                    <th>Place of Dispatch </th>				
                    <td><?=$ewbData->json_data->fromPlace?> - <?=$ewbData->json_data->fromPincode?></td>
                </tr>
                <tr>
                    <th>GSTIN of Recipient </th>				
                    <td><?=$ewbData->json_data->toGstin?> - <?=$ewbData->json_data->toTrdName?></td>
                </tr>
                <tr>
                    <th>Place of Delivery </th>				
                    <td><?=$ewbData->json_data->toPlace?> - <?=$ewbData->json_data->toPincode?></td>
                </tr>
                <tr>
                    <th>Document No. </th>				
                    <td><?=$ewbData->json_data->docNo?></td>
                </tr>
                <tr>
                    <th>Document Date </th>				
                    <td><?=$ewbData->json_data->docDate?></td>
                </tr>
                <tr>
                    <th>Value of Goods </th>				
                    <td><img src="<?=base_url('assets/images/inr.png')?>" width="10"> <?=$ewbData->json_data->totInvValue?></td>
                </tr>
                <tr>
                    <th>Transaction Type </th>				
                    <td><?=$transaction_type[$ewbData->json_data->transactionType]?></td>
                </tr>
                <tr>
                    <th>HSN Code </th>				
                    <td>
                        <?=$ewbData->json_data->mainHsnCode.(((count($ewbData->json_data->itemList) - 1) > 0) ? '  (+'.(count($ewbData->json_data->itemList) - 1). ' Items)' : '')?>
                    </td>
                </tr>
                <tr>
                    <th>Reason for Transportation </th>				
                    <td><?=$supply_type[$ewbData->json_data->supplyType] .' - '.$sub_supply_type[(int)$ewbData->json_data->subSupplyType]?></td>
                </tr>
                <tr>
                    <th>Transporter </th>				
                    <td><?=$ewbData->json_data->transporterId?></td>
                </tr>
            </table>
            
            <table class="table table-bordered m-b-5">
                <tr>
                    <th class="text-center bg-light" colspan="7">PART - B</th>
                </tr>
                <tr>
                    <th>Mode</th>
                    <th>Vehicle / Trans<br>Doc No & Dt</th>
                    <th>From</th>
                    <th>Entered Date</th>
                    <th>Entered By</th>
                    <th>CEWB No. (If any)</th>
                    <th>Multi Veh. Info (If any)</th>
                </tr>
                <tr>
                    <td><?=$trans_mode[$ewbData->json_data->transMode]?></td>
                    <td><?=((!empty($ewbData->json_data->vehicleNo)) ? $ewbData->json_data->vehicleNo : $ewbData->json_data->transporterId)?></td>
                    <td><?=$ewbData->json_data->fromPlace?></td>
                    <td><?=date("d/m/Y<\b\\r />h:i:s A",strtotime($ewbData->eway_bill_date))?></td>
                    <td><?=$ewbData->json_data->fromGstin?></td>
                    <td>-</td>
                    <td>-</td>
                </tr>
            </table>

            <div class="barcode text-center m-b-5 m-t-5">
                <barcode code="601494400839" type="C128A" height="1" text="1" /><br>
                <?=$ewbData->eway_bill_no?>
            </div>
        </div>
	</body>
</html>